name: Continuous Integration
on:
  - push
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          format: html
          additional_args: "--out tfsec.html"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tfsec scan result
          path: tfsec.html
